### ISSUE TITLE
Render URL Meta without Empty Row Between Links

### ISSUE THREAD

**Issue by deepspaceaxolotl** [IsaacAKAJupiter/joplin-url-meta#2]
I'm very grateful for this plugin! It makes keeping track of links much easier, particularly YouTube videos.

From my testing, it seems that it will only render the metadata for one link until an empty row is reached (or the end of the note). So doing the following only results in the first link being rendered:

```
https://example.com/1
text here
https://example.com/2
```
```
https://example.com/1
https://example.com/2
https://example.com/3
```
```
https://example.com/1, https://example.com/2, https://example.com/3
```

The expected behaviour is for it to be rendered immediately after the paragraph it's in, and if there are any other links in the same paragraph, for their metadata to be rendered in order.

**Comment by IsaacAKAJupiter** [comment]
Thanks for using the plugin! I just published an update (may take around 30 minutes for the Joplin Repository to update) that should hopefully fix your problem. The new version released is v1.0.4.

Let me know if the issue persists on the new version, or if it is fixed so I can close the issue.

Thanks!

**Comment by deepspaceaxolotl** [comment]
Seems to be working better now!

It's treating a paragraph as being separated by an empty line, rather than just a newline, is that a Joplin quirk? If not, I'd like to see it render the embeds more like this:
```
https://example.com/1
<embed 1>
https://example.com/2
<embed 2>

https://example.com/3
<embed 3>
```
than this:
```
https://example.com/1
https://example.com/2
<embed 1>
<embed 2>

https://example.com/3
<embed 3>
```

Then again, others might not, so maybe an option could work? Depending on how hard that would be to code.

Thank you!!

**Comment by IsaacAKAJupiter** [comment]
Thanks for the suggestion/idea! I have released another version (v1.0.5) that has a few other bug fixes along with a new setting based on your feedback. See the [version changelog](https://github.com/IsaacAKAJupiter/joplin-url-meta#v105) for the full details.

Let me know if this is what you were looking for or if there are any other issues that arise.

Thanks again!

**Comment by deepspaceaxolotl** [comment]
:D Thank you so much! Just tested it, works well, except that it seems to add an empty row between the embed and the next link in compact mode. If that can be fixed, that'll be that for me!

**Comment by IsaacAKAJupiter** [comment]
Another version has been published (v1.0.6) that should address the spacing issues. It only adds extra space between metadata containers so any extra spacing you see is just how normal Joplin rendering occurs.

Thanks again for using the plugin and providing suggestions! I am going to close this issue; if any other issues arise, don't hesitate to open another issue.

**Comment by deepspaceaxolotl** [comment]
Thanks for developing it!

Hmm, it looks the same to me as before,
```
https://example.com/1
<embed 1>

https://example.com/2
<embed 2>
```
instead of
```
https://example.com/1
<embed 1>
https://example.com/2
<embed 2>
```
which I would expect without an empty row between the links in the markdown, otherwise this doesn't differ visually from adding a row between them. In fact, there seems to be a tiny bit *more* space if there's no empty row between the links? Odd.

**Comment by IsaacAKAJupiter** [comment]
Alright, let's try this one more time. I am now removing the line breaks entirely since they behave differently with plain text/links compared to the meta div container that is inserted. Another release has been pushed (v1.0.7) which _hopefully_ should fix this once and for all!

Thanks again.

**Comment by deepspaceaxolotl** [comment]
It works! Thank you thank you! For your patience and for the fixes! :D
