### ISSUE TITLE
YouTube Playlists No Title or Description Found

### ISSUE THREAD

**Issue by deepspaceaxolotl** [IsaacAKAJupiter/joplin-url-meta#3]
Links to YouTube playlists fail to display a title or description, saying that none were found. Their metadata displays correctly in e.g. Discord.

**Comment by deepspaceaxolotl** [comment]
It sometimes also fails to find the title for other links, where Discord can find them, not sure why. An example where it found the description but not the title: [https://restoration.zora.re/](https://restoration.zora.re/)

**Comment by IsaacAKAJupiter** [comment]
Can you provide me an example link of a YouTube playlist that is not working? I tested with a playlist myself (https://www.youtube.com/playlist?list=PLA3CCrYGqFawo3BuPXD1ZHgINFGV76Vu3) and it seems to be working correctly.

**Comment by deepspaceaxolotl** [comment]
That one doesn't work for me either. Here are the other playlists I've got:

[https://www.youtube.com/playlist?list=PLDV2WEUIxlYM6-V3lJEZmzwPxmTh4xmYt](https://www.youtube.com/playlist?list=PLDV2WEUIxlYM6-V3lJEZmzwPxmTh4xmYt)
[https://www.youtube.com/playlist?list=PL2Dn-v3Oc2aZDHWQ13qe58phfkDcIZJ8H](https://www.youtube.com/playlist?list=PL2Dn-v3Oc2aZDHWQ13qe58phfkDcIZJ8H)
[https://www.youtube.com/playlist?list=PLFPEDTXyQKoNbqs8NEkKbObhIGrVmRhxT](https://www.youtube.com/playlist?list=PLFPEDTXyQKoNbqs8NEkKbObhIGrVmRhxT)
[https://www.youtube.com/playlist?list=PLQDWoXFQ-YLpeEFkzeDZF1MmNQS7BDoI4](https://www.youtube.com/playlist?list=PLQDWoXFQ-YLpeEFkzeDZF1MmNQS7BDoI4)
[https://www.youtube.com/playlist?list=PLgXBK8VQ11v94uRTZARu6aqeCCCUxi1AC](https://www.youtube.com/playlist?list=PLgXBK8VQ11v94uRTZARu6aqeCCCUxi1AC)

**Comment by IsaacAKAJupiter** [comment]
I have just pushed an update (v1.0.8) that should fix the issue with the comment you left before:

> It sometimes also fails to find the title for other links, where Discord can find them, not sure why. An example where it found the description but not the title: https://restoration.zora.re/

As for the YouTube playlists, the update that I pushed will have a new advanced setting for "Debug Copy HTML Content". Please enable that and re-fetch one of the playlists. It will copy the content that I require for debugging to your clipboard. Once you have it on your clipboard, just paste it into [pastebin](https://pastebin.com/) and send me the link to the paste. You can then disable the setting again.

If any other websites are not working for you, just repeat the steps I gave for the YouTube playlists for the broken website and I can take a look!

**Comment by deepspaceaxolotl** [comment]
Thank you! Huh, found a bug with that first link, it wouldn't show the title after refreshing until I removed the link from the note entirely, switched back to the note and then readded it (sadly didn't try without switching to another note first so I can't say if it was just the removal or not). But it works now!

Pastebin isn't letting me post the output, the spam detection keeps getting triggered and it just autodeletes the paste it seems, so [here's a PrivateBin link](https://paste.linux.chat/?6051b969bf75cc1e#AQDHRSuNpanYRUPPK1VozcQVepnZHC3JG6eVU5sSLLQH). It's different this time though, says "Before you continue to YouTube" in the title. That's all I'm getting when I refresh them now.

**Comment by IsaacAKAJupiter** [comment]
> Thank you! Huh, found a bug with that first link, it wouldn't show the title after refreshing until I removed the link from the note entirely, switched back to the note and then readded it (sadly didn't try without switching to another note first so I can't say if it was just the removal or not). But it works now!

Hard to say if it was re-adding or not, but sometimes when new metadata is fetched it will not re-render the markup. You have to either go to a different note and back, or make changes for it to render again. Let me know if you can recreate the bug and what steps you took to do so.

> It's different this time though, says "Before you continue to YouTube" in the title.

There seems to be a page that YouTube is sending you when attempting to fetch the page for the playlist. It probably also happens with normal YouTube videos as well. I've attached an image that is approximately what the page looks like. This is why the metadata is not fetching correctly. I am going to see if I can somehow find a workaround for this or another way of handling YouTube specifically. I will update this issue if I find a solution.

![th-2587669542](https://github.com/user-attachments/assets/43514377-a8a1-48a4-9448-8ac95e122fea)

**Comment by IsaacAKAJupiter** [comment]
I have released a new version (1.0.9) with the following release notes (copied from README.md).

- Added new setting "YouTube Data API v3 Key" to fetch YouTube video (including shorts) and playlist metadata via the API instead of a normal GET request.
  - This fixes [this issue](https://github.com/IsaacAKAJupiter/joplin-url-meta/issues/3)
  - Note, this will most-likely **not** work for private videos/playlists.
  - To get an **API Key**, follow [this](https://developers.google.com/youtube/v3/getting-started) getting started guide by Google.
    - When creating credentials, it may ask you **What data will you be accessing?** For this, choose **Public data**.

Due to limitations, I could not set cookies when fetching metadata via a GET request. Cookies would be required to bypass the consent page (as shown in my previous comment) as that is how Google determines if you have seen the page previously. Because of this, I decided add a setting to resort to the YouTube API to fetch metadata for videos / playlists. The YouTube API requires an API Key, which you will have to get via the guide I provided in the release notes above.

Hopefully this solves your issue and let me know if you have any questions!
I will leave the issue open for now.

**Comment by IsaacAKAJupiter** [comment]
I did want to add another solution that may or may not be applicable to you. If you use a VPN when you are putting the link into the note, the plugin will use the IP of the VPN for the request for the metadata which could bypass the YouTube consent page depending on where your VPN IP is located. For instance, in Canada, I do not get the consent page when requesting YouTube links. So you could use a VPN location for Canada, fetch the metadata for the link, and then turn off the VPN once you are done. This will keep the metadata in the note locally, so you can view it however and whenever you want after it is fetched.

If you use this method, you do not have to provide a YouTube API key if you are not comfortable doing so.

_Note_, not sure if you have tried out any VPNs, but if you have not, please do some research/reading before using/buying one if you plan to use this method.
