### ISSUE TITLE
Option for Default Clicking Behaviour

### ISSUE THREAD

**Issue by deepspaceaxolotl** [IsaacAKAJupiter/joplin-url-meta#4]
Really loving the plugin, it's helped my workflow so much. <3

I was wondering if it could be possible to add an option for what to do when clicking a link that's had metadata loaded for it. Right now, it opens a modal with the metadata and the options to copy the link or open it. I'd like to always open it when I left-click on it, so an option to set a default behaviour (modal, open, copy) would be appreciated!

**Comment by IsaacAKAJupiter** [comment]
Thanks for using the plugin! Glad to hear it has helped.

I have just pushed an update (v1.0.8) that will have a new setting for this.

**Comment by deepspaceaxolotl** [comment]
Thank you so much!!
